---
# tasks file for etcds
- name: install etcd
  yum: name=etcd state=present
- name: cp etcd.service
  template:
    src: etcd.service.j2
    dest: /usr/lib/systemd/system/etcd.service
    mode: 0755
  notify: 
    - reload systemd etcd
    - etcd restart   
- name: etcd enable
  service: name=etcd enabled=yes
  
